locked_names = [
                'ALDAHIR ANTONIO LOPEZ SERAFIN',
                'CANSECO RINES Y LLANTAS',
                'CARLOS ABRAHAM BARAJAS GALINDO',
                'CARLOS IVAN LOZA ANGEL',
                'CESAR RODOLFO COBIAN FLORES',
                'CLAUDIA MONSERRAT PALOMINO LERMA',
                'COMERCIALIZADORA PEGUZA',
                'DANIEL VITAL OCHOA',
                'DIAZ RIZO JUAN CARLOS',
                'DIMAS FERNANDEZ ARIADNA',
                'ECONOLLANTAS SERVICIOS Y ACCESORIOS SA DE CV',
                'EDUARDO GARCIA BLANCO',
                'EMMANUEL CARBAJAL ZEPEDA',
                'ERICK ELKJAER NIEBLA TAMAYO',                
                'GERARDO GARCIA BALVER',
                'GL TIRES GRUP S.A DE C.V.',
                'GONTES LEON JOSE JESUS',
                'GRUPO LOYGA',
                'GRUPO PRODUCE COMUNICACION',
                'GUILLERMO CARDENAS BARRERA',
                'HUGO ALEJANDRO MALDONADO JIMENEZ',  
                'ISABEL CRISTINA GONZALEZ PASTRANA',                
                'JORDAN MISSAEL ROCHA HERNANDEZ',
                'JOSE ANTONIO INZUNZA CORTEZ',
                'JOSE ANTONIO RANGEL CERDA',                
                'JOSUE ERICK DE JESUS URQUIETA RAMIREZ',
                'JP RINES Y LLANTAS S.A. DE C.V.',
                'JUAN CARLOS PALAU GARCIA ROJAS',
                'JUAN MANUEL LEON LLAMAS',
                'JULIAN ALBERTO SAMBRANO',
                'KEVIN YERAY GARCIA MERCADO',
                'LAURA XOCHITL MARTINEZ LARIOS',
                'LLANTAS ROJAVE DE ZACATECAS, CP. ELVIA',
                'LLANTAS Y ACCESORIOS SA DE CV',
                'LLANTERA LOMELI S.A. DE C.V.',
                'LLANTIFRIO',
                'MARIA ESTHER BELLO SEGOVIANO',
                'MARICELA ARENAS MENDOZA',
                'MARISOL GONZALEZ MENDOZA',
                'MAURICIO ALVA MARTINEZ',
                'MELISSA GONZALEZ RUIZ',
                'MENDOZA DEL RIO JAIME',
                'MONTAÑO FIGUEROA ORBELI',
                'MULTISERVICIOS AYON SA DE CV',
                'NABOR ESPINOZA HERRERA',
                'NEUMATICOS Y RINES INDUSTRIALES',
                'ONTIVEROS CAMPOS CIPRIANO',
                'PEREZ CASTRO FRANCISCO EMMANUEL',
                'PEREZ TOVAR JOSE ARTURO',
                'RINES Y LLANTAS AVILA, JORGE AVILA',
                'RINES Y LLANTAS DE GDL',
                'RINES Y LLANTAS MANOLO',
                'RITA MONTOYA SALINAS',
                'RODRIGUEZ RODRIGUEZ JOSE CRUZ',
                'SALVADOR ALBERTO NUÑO BARAJAS',
                'SANCHEZ MORENO JULIO EDUARDO',
                'SYSCOM DE LEON S DE RL DE CV',
                'URIEL OCTAVIO SALINAS DURON',
                'VENTUS SPORT SA DE CV',
                'VIMARSA, S.A. DE C.V.',
                ]