{
    'name': 'ZTYRES - Gestión de Equipo de TI',
    'version': '16.0.1.1.0',
    'summary': 'Inventario, asignaciones, servicios y mantenimiento de equipo de TI',
    'category': 'Tools',
    'author': 'ZTYRES',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'maintenance'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/it_defaults.xml',
        'data/maintenance_cron.xml',
        'views/it_catalog_views.xml',
        'views/it_equipment_views.xml',
        'views/it_mobile_views.xml',
        'views/it_accessory_views.xml',
        'views/it_assignment_views.xml',
        'views/it_service_views.xml',
        'views/it_maintenance_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': True,
}
