from . import zona
from . import unidad
from . import carta_porte_vehicle
from . import vehicle
from . import discount_policy
from . import destino
from . import embarques_stage
from . import embarques_tag
from . import rutas_embarques
from . import embarques
from . import stock_picking
from . import sale_order
from . import res_partner
from . import res_company
from . import account_move
